# name which will be displayed on the workflows in the actions tab in the github
name: Shell commands

# this name will be displayed on the list of the actions in the github
run-name: First the simpliest workflow

# what will be used as a trigger for the action run
on: [push]


# the list of jobs which will be done on the workflow
jobs:
  # this name will be used in the list of the workflow jobs list
  run-shell-commands:
    # defines on which operation system the job will run
    runs-on: ubuntu-latest
    # defines the steps for the job
    steps:
      # the list of steps.
      - name: echo a string
        # defines which command to run. by default bash is used for the linux system
        run: echo "hello world!"
      - name: run several commands
        # example of the several commands in one run
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        # this parameter specifies which shell will be used
        # the list of all shells could be fined in the docs
        shell: python
  
  run-windows-commands:
    runs-on: windows-latest
    needs: ['run-shell-commands']
    steps:
      - name: get current location via bash
        run: pwd
        shell: bash
      - name: get the current location via PowerShell
        run: Get-Location
