name: Shell commands

on: [push]


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world!"
      - name: run several commands
        run: |
          node -v
          npm -v
